org.gradle.jvmargs=-Xmx2G

minecraft_version=26.2
loader_version=0.19.3

mod_version=1.1.0-SNAPSHOT
maven_group=me.playgamesgo
archives_base_name=pvptoggles

fabric_version=0.153.0+26.2
litecommands_version=3.11.1-SNAPSHOT
yacl_version=3.9.5+26.2-fabric
modmenu_version=20.0.0-beta.4
placeholder_api_version=3.1.0-beta.1+26.2
lombok_version=1.18.46
adventure_version=7.0.0

fabric_custom_names_version=0.4.4-26.2
fabric_permissions_api_version=0.7.0